module

public import Mathlib


open Polynomial

--variable {R : Type*} [CommSemiring R]

-- ∀𝒮 ⊆ R × R
-- congruence generated by 𝒮
-- ⇔ 𝒮 を含む R 上の合同関係のうち最小のもの ≝ ⟨𝒮⟩
-- 半環 R 上の合同関係であることを明示する場合は ⟨𝒮⟩_R と書く
-- 合同関係の共通部分は合同関係となるため
-- ⟨𝒮⟩ は 𝒮 を含む R 上のすべての合同関係の共通部分と言い換えられる


--example 2.10


-- ev₀ : R[X] →+* R ; f(X) ↦ f(0)
-- ⇒ ker ev₀ = ⟨(x,0)⟩ が成り立つ

-- proof. (x,0) ∈ ker ev₀ より
-- ⟨(x,0)⟩ ⊆ ker ev₀
-- ∀ f ∈ R[X] ; (f(x),f(0)) ∈ ⟨(x,0)⟩
-- ∵ ∀ a ∈ R , ∀ d ≥ 1
--    (a x^d, 0) = twistProd (a x^(d-1),0) (x, 0) ∈ ⟨(x, 0)⟩
--    f(x) = Σ a_d x^d と書くと
--    (f(x), f(0)) = (Σ a_d x^d, a_0)
--                 = (a_0, a_0) + Σ (a_d x^d, 0) ∈ ⟨(x, 0)⟩
-- ∀ g ∈ ker ev₀,
-- ⇒ f(0) = g(0)
-- ⇒ (f(x), f(0)), (g(0), g(x)) ∈ ⟨(x,0)⟩
-- ⇒ (f(x), g(x)) ∈ ⟨(x,0)⟩
-- ⇒ ker ev₀ ⊆ ⟨(x, 0)⟩
-- ∴ ker ev₀ = ⟨(x, 0)⟩


#check RingCon.coe_sInf
#check RingCon

-- (X,0)から生成される環合同関係
noncomputable def ringConGenX_Zero (R : Type*) [CommSemiring R] : RingCon R[X] :=
  ringConGen (fun a b => a = (X : R[X]) ∧ b = 0)

-- R[X] → R[X] → Prop ⇔ {(a,b) ∈ R[X] × R[X] | Prop} : Set より
-- (fun a b => a = (X : R[X]) ∧ b = 0) は {(a,b) ∈ R[X] × R[X] | a = X ∧ b = 0} = {(X,0)} を意味している。



-- 多項式半環R[X]にX=0を代入する環準同型写像ev₀ : R[X] →+* R, f(X) ↦ f(0)を定義する。
def ev₀ (R : Type*) [CommSemiring R] : R[X] →+* R := Polynomial.evalRingHom (0 : R)


-- ker ev₀ = ⟨(X,0)⟩_R[X]
theorem ker_ev₀_isConGenX_Zero (R : Type*) [CommSemiring R] : (RingCon.ker (ev₀ R))
    = ringConGenX_Zero R := by
  apply le_antisymm
  -- ker ev₀ ⊆ ⟨(X,0)⟩_R[X]
  · intro a b hab;
    -- (a, b) ∈ ker ev₀ ⇒ (a, b) ∈ ⟨(X,0)⟩_R[X]
    -- By definition of $ev₀$, we know that $a.eval 0 = b.eval 0$.

    -- h_eval : a,b ∈ R[X], (a(X),b(X)) ∈ ker ev₀ ⇒ a(0) = b(0)
    have h_eval : a.eval 0 = b.eval 0 := by
      exact hab;
    -- By definition of $ringConGenX_Zero$, we need to show that $a$ and $b$ are related
    --  by the generated equivalence relation.
    -- Polynomial.C : R →+* R[X] ; a ↦ a X^0
    -- Polynomial.eval : R → R[X] → R ; (r,f(X)) ↦ f(r) ; Polynomial.eval ?_ f = f.eval ?_

    -- h_rel : ∀p ∈ R[X], (p(X), p(0)) ∈ ⟨(X,0)⟩_R[X]
    have h_rel : ∀ p : R[X], (ringConGenX_Zero R) p (Polynomial.C (p.eval 0)) := by
      intro p
      -- Polynomial.divX : R[X] → R[X] ; p ↦ p / X
      -- Polynomial.X : R[X] ; X ∈ R[X]
      have h_divX_mul_X_add : p = Polynomial.divX p * Polynomial.X + Polynomial.C (p.coeff 0) := by
        -- p ∈ R[X] ; p = (p / X) * X + p₀
        -- Polynomial.C (p.coeff 0) は p の X^0 項の係数 p₀ を R[X] に埋め込んだもの
        -- ; p / X について p の定数項の除算 p₀ / X = 0 であることに注意

        -- p の X^k 項の係数について取り出し、比較を行う
        ext k
        rcases k with _ | n
        -- k = 0 の場合
        · simp
        -- k = n + 1 の場合 ; つまり k ∈ ℕ>0
        · simp only [coeff_add, coeff_mul_X, coeff_divX, natDegree_C, lt_add_iff_pos_left,
          Order.lt_add_one_iff, zero_le, coeff_eq_zero_of_natDegree_lt, add_zero]
           -- coeff_eq_zero_of_natDegree_lt : p の次数が n より小さい場合、p の X^n 項の係数は 0 である.
           -- p.coeff (n + 1) = (p.divX * X + C (p.coeff 0)).coeff (n + 1)
           -- 右辺 = (p.divX * X + C (p.coeff 0)).coeff (n + 1)
           -- = (p/divX * X).coeff (n + 1) + (C (p.coeff 0)).coeff (n + 1) ; coeff_add
           -- = (p/divX).coeff n + 0 ; coeff_mul_X, coeff_divX, natDegree_C, coeff_eq_zero_of_natDegree_lt
           -- k > 0 より (p / divX).coeff n = p.coeff (n + 1)
           -- よって左辺=右辺...ということをsimpでやっていると予想

      -- Since $X ∼ 0$, we have $p.divX * X ∼ 0$.
      -- p.divX * X は p の定数項を消していることに注意
      have h_divX_mul_X : (ringConGenX_Zero R) (Polynomial.divX p * Polynomial.X) 0 := by
        have h_divX_mul_X : (ringConGenX_Zero R) (Polynomial.X) 0 := by
          exact RingConGen.Rel.of _ _ ⟨ rfl, rfl ⟩;
        simpa using RingConGen.Rel.mul ( RingConGen.Rel.refl _ ) h_divX_mul_X;
      -- (ringConGenX_Zero R) p (C (eval 0 p)) ; ⊢
      -- p₀ ∼ p₀ ; RingConGen.Rel.refl (C ( p.coeff 0 ) )
      -- p.divX * X ∼ 0 ; h_divX_mul_X
      -- p.divX * X + p₀ (=p) ∼ 0 + p₀ ; RingConGen.Rel.add (RingConGen.Rel.refl _) h_divX_mul_X
      -- p ∼ 0 + p₀ より p₀ = p(0) を示せば Goal の形となる
      convert RingConGen.Rel.add h_divX_mul_X ( RingConGen.Rel.refl ( C ( p.coeff 0 ) ) );
      -- p = p.divX * X + C (p.coeff 0) ; h_divX_mul_X_add
      -- よって p(0) = 0 + C (p.coeff 0)
      simp only [coeff_zero_eq_eval_zero, zero_add]
    -- (ringConGenX_Zero R) a (C (eval 0 a))
    have := h_rel a
    -- (ringConGenX_Zero R) b (C (eval 0 b))
    have := h_rel b
    -- RingCon.ker_apply ; ConKerの定義(a ∼ b ⇔ f(a) = f(b))
    simp_all only [RingCon.ker_apply]
    exact this.trans ( RingCon.symm _ ( h_rel b ) )

  -- ker ev₀ ⊇ ⟨(X,0)⟩_R[X]
  · intro a b hab;
    -- (a, b) ∈ ⟨(X,0)⟩_R[X] ⇒ (a, b) ∈ ker ev₀
    induction hab;
    all_goals simp_all [ ev₀, RingCon.ker ]




-- Theorem 2.11

-- Suppose R is a semiring and S ⊆ R × R satisfies properties (E1), (E2), (I1),
-- and (I2). Then ⟨𝒮⟩ consists of all pairs (f, g) for which there exists a finite transitive
-- chain (f, r1), (r1, r2), ..., (rn−1, rn), (rn, g) ∈ 𝒮

-- 環におけるイデアルの場合とは異なり、有限個の生成元から生成される合同関係（congruence）の一般の元は、必ずしも生成元の「和とその倍」の形で表すことはできない。
-- 一般に、推移律（transitivity）の性質のために、生成元だけを用いた記述は複雑になる。

-- しかし、次のことは言える。

-- 補題 2.11.
-- R を半環（semiring）とし、S⊆R×R が性質 (E1)、(E2)、(I1)、および (I2) を満たすとする。
-- このとき、S によって生成される合同関係 ⟨S⟩ は、次のようなすべての組 (f,g) からなる。
-- (f,r1),(r1,r2),...,(rn−1,rn),(rn,g) ∈ S

-- すなわち、ある有限個の元
-- r1, r2, ..., rn ∈ R が存在して、
-- (f, r1), (r1, r2), ..., (rn−1, rn), (rn, g) ∈ S
-- となる有限の推移鎖（finite transitive chain）が存在するとき、かつそのときに限り、
-- (f, g) ∈ ⟨𝒮⟩ である。


-- 合同関係の一般の元が生成元の「和とその倍」の形で表せない具体例としては、(a,c) ∈ ⟨{(a,b),(b,c)}⟩を考えると(a,c)は(a,b)と(b,c)の和や倍では表せない。
-- 推移律の性質を生成元だけを用いて行うのは複雑である、というモチベーション。

-- つまり 推移律を仮定していないSに対して、Sから生成される合同関係の元は、Sの元を推移的なchainで結んだものとして与えられる。
-- 上記の例においては(a,c) ∈ ⟨{(a,b),(b,c)}⟩について、(a,c)は推移律を仮定しない{(a,b),(b,c)}上では生成元とrefl,symm,add,mulの形で表せない。
-- しかし、推移的なchainの性質を通して、(a,b),(b,c) ∈ S のchainが存在することからSの元(a,c)を生成元とtransの形で表すことができる。



open scoped BigOperators
open scoped Classical
open Relation
/-!
# Congruence generated by a compatible reflexive-symmetric relation on a semiring
We consider a semiring `R` and a relation `E : R → R → Prop` (a subset of `R × R`)
satisfying:
* `(E1)` reflexivity: `∀ a, E a a`;
* `(E2)` symmetry: `∀ a b, E a b → E b a`;
* `(I1)` additive compatibility: `E a b → E a' b' → E (a + a') (b + b')`;
* `(I2)` multiplicative compatibility: `E a b → E a' b' → E (a * a') (b * b')`.
The congruence generated by `E`, namely `ringConGen E`, then consists exactly of the
pairs `(f, g)` connected by a finite transitive chain
`E f r₁, E r₁ r₂, …, E rₙ g`, i.e. `Relation.TransGen E f g`.
-/
namespace SemiringCongruence


variable {R : Type*} [Semiring R] (E : R → R → Prop)

/-- Additive compatibility lifts along transitive chains. -/
lemma transGen_add
    (E1 : ∀ a, E a a)
    (I1 : ∀ a b a' b', E a b → E a' b' → E (a + a') (b + b'))
    {a b a' b' : R} (h : TransGen E a b) (h' : TransGen E a' b') :
    TransGen E (a + a') (b + b') := by
  induction h
  · induction h'
    · exact .single (I1 _ _ _ _ ‹_› ‹_›)
    · exact TransGen.tail ‹_› (I1 _ _ _ _ (E1 _) ‹_›)
  · exact .trans ‹_› (.single <| I1 _ _ _ _ ‹_› (E1 _))

/-- Multiplicative compatibility lifts along transitive chains. -/
lemma transGen_mul
    (E1 : ∀ a, E a a)
    (I2 : ∀ a b a' b', E a b → E a' b' → E (a * a') (b * b'))
    {a b a' b' : R} (h : TransGen E a b) (h' : TransGen E a' b') :
    TransGen E (a * a') (b * b') := by
  induction h
  · induction h'
    · exact .single (I2 _ _ _ _ ‹_› ‹_›)
    · exact TransGen.tail ‹_› (I2 _ _ _ _ (E1 _) ‹_›)
  · exact .trans ‹_› (.single <| I2 _ _ _ _ ‹_› (E1 _))

/-- The ring congruence whose underlying relation is the transitive closure of `E`. -/
def chainCon
    (E1 : ∀ a, E a a)
    (E2 : ∀ a b, E a b → E b a)
    (I1 : ∀ a b a' b', E a b → E a' b' → E (a + a') (b + b'))
    (I2 : ∀ a b a' b', E a b → E a' b' → E (a * a') (b * b')) : RingCon R where
  r := TransGen E
  iseqv :=
    { refl := fun a => TransGen.single (E1 a)
      symm := fun h => TransGen.symmetric (fun x y => E2 x y) h
      trans := fun h h' => h.trans h' }
  mul' := fun h h' => transGen_mul E E1 I2 h h'
  add' := fun h h' => transGen_add E E1 I1 h h'

/-- **Main theorem.** The congruence generated by a reflexive, symmetric, additively and
multiplicatively compatible relation `E` on a semiring consists of exactly the pairs
`(f, g)` joined by a finite transitive chain in `E`. -/
theorem ringConGen_eq_transGen
    (E1 : ∀ a, E a a)
    (E2 : ∀ a b, E a b → E b a)
    (I1 : ∀ a b a' b', E a b → E a' b' → E (a + a') (b + b'))
    (I2 : ∀ a b a' b', E a b → E a' b' → E (a * a') (b * b'))
    (f g : R) :
    ringConGen E f g ↔ TransGen E f g := by
  constructor
  · intro h
    have hle : ringConGen E ≤ chainCon E E1 E2 I1 I2 :=
      RingCon.ringConGen_le (fun x y hxy => TransGen.single hxy)
    exact hle h
  · intro h
    induction h with
    | single hxy => exact RingConGen.Rel.of _ _ hxy
    | tail _ hbc ih => exact ih.trans (RingConGen.Rel.of _ _ hbc)


end SemiringCongruence

-- ヒルベルトの零点定理　：　目標

namespace SemiringCongruence'

variable (R : Type*) [Semiring R]

structure RingReflSymm where
  r : R → R → Prop
  refl : ∀ a, r a a
  symm : ∀ {a b}, r a b → r b a
  add : ∀ {a b c d}, r a b → r c d → r (a + c) (b + d)
  mul : ∀ {a b c d}, r a b → r c d → r (a * c) (b * d)

-- def RingReflSymm.ofRingCon (C : RingCon R) : RingReflSymm R where
--   r := C
--   refl := C.refl
--   symm := C.symm
--   add := @C.add
--   mul := @C.mul

-- memo show_term を入れると<_>とかの中身が見れる

variable {R}
-- これを入れないとC : RingReflSymm R のTypeが Type u+1 と Type (?u.15456 + 1) で
-- 一致しないと怒られる.

-- コメントの変数はexpose_namesで展開されたものではなく記述している場合がある
theorem transGen_add (C : RingReflSymm R)
    {a b a' b' : R} (h : TransGen C.r a b) (h' : TransGen C.r a' b') :
    TransGen C.r (a + a') (b + b') := by
  -- h : TransGen C.r a b
  induction h
  -- h => b_1 : R
  --      h : C.r a b_1
    -- h' : TransGen C.r a' b'
  · induction h'
    -- h' => b_2 : R
    --       h_1 : C.r a' b_2
    · expose_names
      apply TransGen.single (C.add h h_1)
    -- h =>  b_1 : R
    --       h : C.r a b_1
    -- h' => b_2 c : R
    --       h_1 : TransGen C.r a' b_2
    --       h_2 : C.r b_2 c
    --       a_ih : TransGen C.r (a + a') (b_1 + b_2)
    · expose_names
      apply TransGen.tail a_ih (C.add (C.refl b_1) h_2)
  -- h' : TransGen C.r a' b'
  -- h => b_1 c : R
  --      h : TransGen C.r a b_1
  --      h_1 : C.r b_1 c
  --      a_ih : TransGen C.r (a + a') (b_1 + b')
  · expose_names
    apply TransGen.trans a_ih (TransGen.single (C.add h_1 (C.refl b')))

theorem transGen_mul (C : RingReflSymm R)
    {a b a' b' : R} (h : TransGen C.r a b) (h' : TransGen C.r a' b') :
    TransGen C.r (a * a') (b * b') := by
  induction h
  · induction h'
    · expose_names
      apply TransGen.single (C.mul h h_1)
    · expose_names
      apply TransGen.tail a_ih (C.mul (C.refl b_1) h_2)
  · expose_names
    apply TransGen.trans a_ih (TransGen.single (C.mul h_1 (C.refl b')))

def chainCon (C : RingReflSymm R) : RingCon R where
  r := TransGen C.r
  iseqv :=
    { refl := fun a => TransGen.single (C.refl a)
      symm := fun h => sorry
      trans := fun h h' => h.trans h' }
  mul' := fun h h' => transGen_mul C h h'
  add' := fun h h' => transGen_add C h h'


theorem ringConGen_eq_TransGen (C : RingReflSymm R) (f g : R) :
    ringConGen C.r f g ↔ TransGen C.r f g := by
  constructor
  · sorry
  · sorry

end SemiringCongruence'
